package ocp._00_utils;

public enum Chapter {
	JAVA_CLASS_DESIGN,
	ADVANCED_JAVA_CLASS_DESIGN,
	GENERICS_AND_COLLECTIONS,
	LAMBDA_BUILTIN_FUNCTIONAL_INTERFACES,
	JAVA_STREAM_API,
	EXCEPTIONS_AND_ASSERTIONS,
	USE_JAVA_SE_8_DATE_TIME_API,
	JAVA_IO_FUNDAMENTALS,
	JAVA_FILE_IO_NIO_2,
	JAVA_CONCURRENCY,
	BUILDING_DATABASE_APPLICATIONS_WITH_JDBC,
	LOCALIZATION
}